export const sideBarLp: any[] = [
  {
    label: "Atividades",
    link: "/atividades",
    icon: "atividades",
    web: true,
  },
  {
    label: "Quem Somos",
    link: "/quem-somos",
    icon: "quemSomos",
    web: true,
  },
  {
    label: "Seja um parceiro B2",
    link: "/parceiro",
    icon: "parceiros",
    web: true,
  },
  {
    label: "Fale Conosco",
    link: "/fale-conosco",
    icon: "email",
    web: true,
  },
  {
    label: "Logar-se",
    link: "/login",
    icon: "logar",
    web: false,
  },
];

export const sideBarClient: any[] = [
  {
    label: "Perfil",
    link: "/perfil",
    icon: "perfil",
    web: false,
    menu: true,
  },
  {
    label: "Atividades",
    link: "/atividades",
    icon: "atividades",
    web: true,
  },
  {
    label: "Notificações",
    link: "/notificacoes",
    icon: "notificacoes",
    web: true,
  },
  {
    label: "Favoritos",
    link: "/informacoes",
    icon: "favoritos",
    tab: "favoritos",
    web: false,
    menu: true,
  },
  {
    label: "Histórico de Atividades",
    link: "/informacoes",
    icon: "duracao",
    tab: "historico",
    web: false,
    menu: true,
  },
  {
    label: "Reservas",
    link: "/informacoes",
    icon: "reservas",
    tab: "reservas",
    web: false,
    menu: true,
  },
  {
    label: "Galeria de Fotos",
    link: "/galeria-de-fotos",
    icon: "camera",
    tab: "galeria",
    web: false,
    menu: true,
  },
  {
    label: "Carrinho de Compras",
    link: "/carrinho",
    icon: "carrinho",
    web: true,
  },
  {
    label: "Chat",
    link: "/chat",
    icon: "chat",
    web: true,
    menu: true,
  },
  {
    label: "Fale Conosco",
    link: "/fale-conosco",
    icon: "email",
    web: false,
    menu: true,
  },
  {
    label: "Sair",
    link: "/",
    icon: "sair",
    web: false,
    menu: true,
  },
];

export const sideBarPartnet: any[] = [
  {
    label: "Perfil",
    link: "/perfil",
    icon: "perfil",
    web: false,
    menu: true,
  },
  {
    label: "Atividades",
    link: "/parceiro/minhas-atividades",
    icon: "atividades",
    web: true,
  },
  {
    label: "Fotos de passeios",
    link: "/parceiro/fotos-de-passeios",
    icon: "camera",
    web: false,
    menu: true,
  },
  {
    label: "Notificações",
    link: "/notificacoes",
    icon: "notificacoes",
    web: true,
  },
  {
    label: "Atividades Cadastradas",
    link: "/parceiro/atividades-cadastradas",
    icon: "home",
    web: false,
    menu: true,
  },
  {
    label: "Reservas",
    link: "/parceiro/reservas",
    icon: "reservas",
    web: false,
    menu: true,
  },
  {
    label: "Financeiro",
    link: "/parceiro/financeiro",
    icon: "pie",
    web: true,
    menu: true,
  },
  {
    label: "Chat",
    link: "/chat",
    icon: "chat",
    web: true,
  },
  {
    label: "Fale Conosco",
    link: "/fale-conosco",
    icon: "email",
    web: false,
    menu: true,
  },
  {
    label: "Sair",
    link: "/",
    icon: "sair",
    web: false,
    menu: true,
  },
];

export const sideBarAdmin: any[] = [
  {
    label: "Perfil",
    link: "/perfil",
    icon: "perfil",
    web: false,
  },
  {
    label: "Home",
    link: "/admin",
    icon: "home",
    web: true,
  },
  {
    label: "Avaliações de Atividades",
    link: "/admin/avaliacoes",
    icon: "basic-star",
    web: true,
  },
  {
    label: "Pagamento de parceiros",
    link: "/admin/pagamento-parceiros",
    icon: "payment",
    web: false,
  },
  {
    label: "Parceiros Cadastradaos",
    link: "/admin/parceiros-cadastrados",
    icon: "parceiros",
    tab: "parceiros",
    web: false,
  },
  {
    label: "Notificações",
    link: "/admin/notificacoes",
    icon: "notificacoes",
    tab: "notificacoes",
    web: false,
  },
  {
    label: "Financeiro",
    link: "/admin/financeiro",
    icon: "pie",
    web: true,
  },
  {
    label: "Chat",
    link: "/chat",
    icon: "chat",
    web: true,
  },
  {
    label: "Configurações",
    link: "/admin/configuracoes",
    icon: "config",
    web: true,
  },
  {
    label: "Sair",
    link: "/",
    icon: "sair",
    web: false,
  },
];
